FROM plone/plone-backend:6
RUN /app/bin/pip install pas.plugins.imio wrapt authomatic==1.0.0 pas.plugins.authomatic jwcrypto deprecated cryptography cffi pycparser plone.app.changeownership setuptools --no-deps
RUN /app/bin/pip install z3c.jbot
