version: '2'

services:
  localauthentic:
    build:
      context: authentic
      dockerfile: Dockerfile
    image: sso:latest
    mem_limit: 2048m
    ports:
        - "80:80"
    extra_hosts:
        local.example.net:
          127.0.0.1
        local-portail-agent.example.net:
          127.0.0.1
        local-auth.example.net:
          127.0.0.1
        local-hobo.example.net:
          127.0.0.1
    volumes:
      - ./data/hobo:/var/lib/hobo/tenants
      - ./data/combo:/var/lib/combo/tenants
      - ./data/authentic2:/var/lib/authentic2-multitenant/tenants
      - ./config/nginx:/etc/nginx/sites-available
      - ./config/combo:/etc/combo
      - ./config/authentic2:/etc/authentic2-multitenant
      - ./config/hobo:/etc/hobo
      - ./config/hobo-agent:/etc/hobo-agent
      - ./src:/opt/publik
    command: /bin/sh -c "sleep 10 ; /run.sh"
    depends_on:
      - database
      - rabbitmq
  rabbitmq:
    image: rabbitmq
    hostname: rabbitmq
  database:
    image: postgres
    hostname: postgres
    volumes:
      - ./data/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
    environment:
      - "POSTGRES_PASSWORD=password"
  memcached:
    image: memcached
    hostname: memcached
