version: '2.4'

services:
  authentic:
    build:
      context: sso
      dockerfile: Dockerfile
    image: wc/sso:latest
    environment:
      - AGENTS_HOSTNAME=agents.wc.localhost
      - USAGERS_HOSTNAME=usagers.wc.localhost
    mem_limit: 2048m
    expose:
      - 80
    #ports:
    #    - "80:80"
    extra_hosts:
      hobo-agents.wc.localhost:
        127.0.0.1
      agents.wc.localhost:
        127.0.0.1
      combo-agents.wc.localhost:
        127.0.0.1
      backoffice-agents.wc.localhost:
        127.0.0.1
      hobo-usagers.wc.localhost:
        127.0.0.1
      usagers.wc.localhost:
        127.0.0.1
      combo-usagers.wc.localhost:
        127.0.0.1
      backoffice-usagers.wc.localhost:
        127.0.0.1
    volumes:
      - ./data/hobo:/var/lib/hobo/tenants
      - ./data/combo:/var/lib/combo/tenants
      - ./data/authentic2-multitenant:/var/lib/authentic2-multitenant/tenants
      - ./config/combo/settings.d:/etc/combo/settings.d
      - ./config/authentic2-multitenant:/etc/authentic2-multitenant
      - ./config/hobo/settings.d:/etc/hobo/settings.d
      - ./config/hobo-agent/settings.d:/etc/hobo-agent/settings.d
      - ./config/nginx:/etc/nginx/sites-available
      - ./src:/opt/publik
      - ./sso/agents.json:/agents.json
      - ./sso/usagers.json:/usagers.json
      - ./sso/index.json:/index.json
    command: >
      /bin/sh -c "
        echo Waiting for rabbitmq and postgres services start...;
        while ! nc -z rabbitmq 5672;
        do
          sleep 3;
        done;
        echo Connected!;
        /run.sh;
      "  
    depends_on:
      - database
      - rabbitmq
      - memcached
      - reverse-proxy
    labels:
      - "traefik.http.routers.authentic.rule=HostRegexp(`wc.localhost`, `{subdomain:[a-z]+-+[a-z]+}.wc.localhost`) || Host(`agents.wc.localhost`) || Host(`usagers.wc.localhost`)"
  rabbitmq:
    image: rabbitmq
    hostname: rabbitmq
  database:
    image: postgres
    hostname: database
    volumes:
      - ./data/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
    environment:
      - "POSTGRES_PASSWORD=password"
  memcached:
    image: memcached
    hostname: memcached
  plone4:
    build:
      context: plone4
      dockerfile: Dockerfile
    image: plone4
    expose:
      - 8080
    #ports:
    #  - "8084:8080"
    environment:
      zope_i18n_compile_mo_files: "true"
      TZ: "Europe/Brussels"
      ENV: "dev"
      PLONE_CSRF_DISABLED: "true"
      consumer_key_usagers: "client-id-plone4-wcu"
      consumer_key_agents: "client-id-plone4-wca"
      consumer_secret_usagers: "client-secret-plone4-wcu"
      consumer_secret_agents: "client-secret-plone4-wca"
      authentic_usagers_hostname: "usagers.wc.localhost"
      authentic_agents_hostname: "agents.wc.localhost"
      service_ou: "0841470248"
      service_slug: "plone4-iasmartweb"
    volumes:
      - plone4-data:/data
    labels:
      - "traefik.http.routers.plone4.rule=Host(`plone4.localhost`)"
      #- 'traefik.http.services.plone4.loadbalancer.server.port=8084'
      - "traefik.http.routers.plone4.middlewares=add-plone"
      - "traefik.http.middlewares.add-plone.addprefix.prefix=/VirtualHostBase/http/plone4.localhost/Plone/VirtualHostRoot"
  reverse-proxy:
    image: traefik:2.2
    command:
      #- "--log.level=DEBUG"
      - '--api.insecure=true'
      - '--providers.docker'
      - '--entryPoints.web.address=:80'
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  plone4-data:
