version: '2.4'

services:
  # plone4:
  #   build:
  #     context: plone4
  #     dockerfile: Dockerfile
  #   image: plone4
  #   links:
  #     - authentic:agents.dev.publik.love
  #     - authentic:usagers.dev.publik.love
  #   expose:
  #     - 8080
  #   environment:
  #     zope_i18n_compile_mo_files: "true"
  #     TZ: "Europe/Brussels"
  #     ENV: "dev"
  #     PLONE_CSRF_DISABLED: "true"
  #     consumer_key_usagers: "client-id-plone4-wcu"
  #     consumer_key_agents: "client-id-plone4-wca"
  #     consumer_secret_usagers: "client-secret-plone4-wcu"
  #     consumer_secret_agents: "client-secret-plone4-wca"
  #     authentic_usagers_hostname: "usagers.dev.publik.love"
  #     authentic_agents_hostname: "agents.dev.publik.love"
  #     service_ou: "0841470248"
  #     service_slug: "plone4-iasmartweb"
  #   volumes:
  #     - plone4-data:/data
  #   command: bin/instance fg
  plone6:
    build:
       context: plone6
       dockerfile: Dockerfile
    image: plone6
    links:
      - authentic:agents.dev.publik.love
      - authentic:usagers.dev.publik.love
    ports:
      - "8080:8080"
    environment:
      TYPE: "classic"
      SITE: "Plone"
      PROFILES: "pas.plugins.imio:default"
      DELETE_EXISTING: false
      LANGUAGE: "fr"
      TIMEZONE: "Europe/Brussels"
      TZ: "Europe/Brussels"
      PLONE_CSRF_DISABLED: "true"
      consumer_key_usagers: "client-id-plone6-wcu"
      consumer_key_agents: "client-id-plone6-wca"
      consumer_secret_usagers: "client-secret-plone6-wcu"
      consumer_secret_agents: "client-secret-plone6-wca"
      authentic_usagers_hostname: "usagers.dev.publik.love"
      authentic_agents_hostname: "agents.dev.publik.love"
      service_ou: "0841470248"
      service_slug: "plone6-iasmartweb"
    volumes:
      - plone6-data:/data
  cypress:
    image: cypress/included:12.10.0
    volumes:
      - ./cypress:/e2e/cypress
      - ./cypress.config.js:/e2e/cypress.config.js
    working_dir: /e2e
    depends_on:
      authentic:
        condition: service_healthy
      # plone4:
      #   condition: service_healthy
      plone6:
        condition: service_healthy
    links:
      - plone6:plone6.dev.publik.love
      - authentic:agents.dev.publik.love
      - authentic:combo-agents.dev.publik.love
    # command: --browser firefox

volumes:
  # plone4-data:
  plone6-data:

networks:
  external:
    external: true