version: '2.4'

services:
  plone4:
    build:
      context: plone4
      dockerfile: Dockerfile
    image: plone4
    links:
      - authentic:agents.wc.localhost
      - authentic:usagers.wc.localhost
    expose:
      - 8080
    environment:
      zope_i18n_compile_mo_files: "true"
      TZ: "Europe/Brussels"
      ENV: "dev"
      PLONE_CSRF_DISABLED: "true"
      consumer_key_usagers: "client-id-plone4-wcu"
      consumer_key_agents: "client-id-plone4-wca"
      consumer_secret_usagers: "client-secret-plone4-wcu"
      consumer_secret_agents: "client-secret-plone4-wca"
      authentic_usagers_hostname: "usagers.wc.localhost"
      authentic_agents_hostname: "agents.wc.localhost"
      service_ou: "0841470248"
      service_slug: "plone4-iasmartweb"
    volumes:
      - plone4-data:/data
    labels:
      - "traefik.http.routers.plone4.rule=Host(`plone4.localhost`)"
      - "traefik.http.routers.plone4.middlewares=add-plone"
      - "traefik.http.middlewares.add-plone.addprefix.prefix=/VirtualHostBase/http/plone4.localhost/Plone/VirtualHostRoot"
  plone5:
    build:
      context: plone5
      dockerfile: Dockerfile
    image: plone5
    links:
      - authentic:agents.wc.localhost
      - authentic:usagers.wc.localhost
    expose:
      - 8080
    environment:
      zope_i18n_compile_mo_files: "true"
      TZ: "Europe/Brussels"
      ENV: "dev"
      PLONE_CSRF_DISABLED: "true"
      consumer_key_usagers: "client-id-plone5-wcu"
      consumer_key_agents: "client-id-plone5-wca"
      consumer_secret_usagers: "client-secret-plone5-wcu"
      consumer_secret_agents: "client-secret-plone5-wca"
      authentic_usagers_hostname: "usagers.wc.localhost"
      authentic_agents_hostname: "agents.wc.localhost"
      service_ou: "0841470248"
      service_slug: "plone5-iasmartweb"
    volumes:
      - plone5-data:/data
    labels:
      - "traefik.http.routers.plone5.rule=Host(`plone5.localhost`)"
      - "traefik.http.routers.plone5.middlewares=add-plone5"
      - "traefik.http.middlewares.add-plone5.addprefix.prefix=/VirtualHostBase/http/plone5.localhost/Plone/VirtualHostRoot"
  cypress:
    image: cypress/included:12.10.0
    volumes:
      - ./cypress:/e2e/cypress
      - ./cypress.config.js:/e2e/cypress.config.js
    working_dir: /e2e
    depends_on:
      authentic:
        condition: service_healthy
      plone4:
        condition: service_healthy
      plone5:
        condition: service_healthy
    links:
      - reverse-proxy:plone4.localhost
      - reverse-proxy:plone5.localhost
      - reverse-proxy:agents.wc.localhost
      - reverse-proxy:combo-agents.wc.localhost
    command: --browser firefox
volumes:
  plone4-data:
  plone5-data:
