version: '2.4'

services:
  plone4:
    build:
      context: plone4
      dockerfile: Dockerfile
    image: plone4
    links:
      - authentic:agents.wc.localhost
      - authentic:usagers.wc.localhost
    expose:
      - 8080
    environment:
      zope_i18n_compile_mo_files: "true"
      TZ: "Europe/Brussels"
      ENV: "dev"
      PLONE_CSRF_DISABLED: "true"
      consumer_key_usagers: "client-id-plone4-wcu"
      consumer_key_agents: "client-id-plone4-wca"
      consumer_secret_usagers: "client-secret-plone4-wcu"
      consumer_secret_agents: "client-secret-plone4-wca"
      authentic_usagers_hostname: "usagers.wc.localhost"
      authentic_agents_hostname: "agents.wc.localhost"
      service_ou: "0841470248"
      service_slug: "plone4-iasmartweb"
    volumes:
      - plone4-data:/data
    labels:
      - "traefik.http.routers.plone4.rule=Host(`plone4.localhost`)"
      - "traefik.http.routers.plone4.middlewares=add-plone"
      - "traefik.http.middlewares.add-plone.addprefix.prefix=/VirtualHostBase/http/plone4.localhost/Plone/VirtualHostRoot"

  cypress:
    #build:
    #  context: cypress
    #image: automation
    image: cypress/included:4.11.0
    volumes:
      - ./cypress:/cypress
      - ./cypress.json:/cypress.json
    depends_on:
      - authentic
      - plone4
    links:
      - reverse-proxy:plone4.localhost
      - reverse-proxy:agents.wc.localhost
      - reverse-proxy:combo-agents.wc.localhost
    command: --browser chrome
  reverse-proxy:
    ports:
      - "80"



volumes:
  plone4-data:
