# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * 1' # Every mondays at 02:00
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Create testing env
        run: |
          make build-no-cache
          make testing-env
          docker compose ps

      - name: Start Cypress tests
        run: make run-cypress

      # Upload Cypress videos
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos

      - name: Login to DockerHub
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD

      - name: Push to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker tag wc/sso imiobe/authentic:$(date +%Y%m%d%H%M)
          docker tag wc/sso imiobe/authentic:latest
          docker push imiobe/authentic
