# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 1 * * 1' # Every mondays at 01:00
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on:
      group: self-hosted

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Create testing env
        run: |
          sudo apt update
          sudo apt install -y make
          make build-no-cache
          make testing-env
          docker compose ps
          ls -lah
          ls -lah cypress

      - name: Start Cypress tests
        run: |
          ls -lah cypress
      #     make run-cypress

      # # Upload Cypress videos
      # - uses: actions/upload-artifact@v1
      #   if: always()
      #   with:
      #     name: cypress-videos
      #     path: cypress/videos

      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.HARBOR_URL }}
          username: ${{ secrets.COMMON_HARBOR_USERNAME }}
          password: ${{ secrets.COMMON_HARBOR_PASSWORD }}
      - name: waco
        uses: docker/build-push-action@v2.5.0
        with:
          context: sso
          tags: ${{ secrets.HARBOR_URL }}/common/waco:latest
          platforms: linux/amd64
          pull: true
          push: true